# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PitoTui < Formula
  desc "Terminal client for PITO, the self-hosted YouTube channel manager"
  homepage "https://github.com/gmrdad82/pito-tui"
  version "4.0.1"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v4.0.1/pito-tui_4.0.1_darwin_amd64.tar.gz"
      sha256 "fa2be69d68cd5f0509152eb6707149408dfce596baf753a19bc39cdd99501e72"

      define_method(:install) do
        bin.install "pito-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v4.0.1/pito-tui_4.0.1_darwin_arm64.tar.gz"
      sha256 "47b5a20ee75b035b988ec508ec53e5840dfe67a0d8d9b555f68c3d6af8c72a34"

      define_method(:install) do
        bin.install "pito-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v4.0.1/pito-tui_4.0.1_linux_amd64.tar.gz"
      sha256 "665fb3def1f9b0b1f6a09b0652adbadff9679d667b675aea4dc67635b5828d57"
      define_method(:install) do
        bin.install "pito-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v4.0.1/pito-tui_4.0.1_linux_arm64.tar.gz"
      sha256 "289b523a150f0ad121dbaf2f5ba48141c48b05619f084f61a9348ff580ac2aa2"
      define_method(:install) do
        bin.install "pito-tui"
      end
    end
  end

  test do
    system "#{bin}/pito-tui", "version"
  end
end
