# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PitoTui < Formula
  desc "Terminal client for PITO, the self-hosted YouTube channel manager"
  homepage "https://github.com/gmrdad82/pito-tui"
  version "2.3.1"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v2.3.1/pito-tui_2.3.1_darwin_amd64.tar.gz"
      sha256 "b44529ce5a41984186f08e50decbb5643ca65d82d2b828668a6f7bfffb6d1cf2"

      define_method(:install) do
        bin.install "pito-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v2.3.1/pito-tui_2.3.1_darwin_arm64.tar.gz"
      sha256 "a6e494d5e748704db3c8a7396daec4c92493f5b4b6e5c2f55c261ed42e9018e5"

      define_method(:install) do
        bin.install "pito-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v2.3.1/pito-tui_2.3.1_linux_amd64.tar.gz"
      sha256 "b2843f2facb9d94c6497f32695df56fa250aed863fb65d5499f813ae5b3e5f05"
      define_method(:install) do
        bin.install "pito-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v2.3.1/pito-tui_2.3.1_linux_arm64.tar.gz"
      sha256 "89e7efa570278c69c38da4657ce32646304bd3184b85633e44be33fa75e84f0a"
      define_method(:install) do
        bin.install "pito-tui"
      end
    end
  end

  test do
    system "#{bin}/pito-tui", "version"
  end
end
