# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PitoTui < Formula
  desc "Terminal client for PITO, the self-hosted YouTube channel manager"
  homepage "https://github.com/gmrdad82/pito-tui"
  version "2.0.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v2.0.0/pito-tui_2.0.0_darwin_amd64.tar.gz"
      sha256 "f6537e900717e103e1e80177713b9faa739458c566c96f2299067327803e30d5"

      define_method(:install) do
        bin.install "pito-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v2.0.0/pito-tui_2.0.0_darwin_arm64.tar.gz"
      sha256 "726b6c0c2e2e510a067b5cf5541aa2cf2afefeae85f72115c3f1852cef432f84"

      define_method(:install) do
        bin.install "pito-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v2.0.0/pito-tui_2.0.0_linux_amd64.tar.gz"
      sha256 "fafdd00cba8a222a6b602bc438a5aea4593422a8b452ab3cead900892529a3cc"
      define_method(:install) do
        bin.install "pito-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmrdad82/pito-tui/releases/download/v2.0.0/pito-tui_2.0.0_linux_arm64.tar.gz"
      sha256 "2cd945ffb1882c4486b06cd71e69a13a4f18000d95ef4e2c7fbe898af69fcdc4"
      define_method(:install) do
        bin.install "pito-tui"
      end
    end
  end

  test do
    system "#{bin}/pito-tui", "version"
  end
end
